import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Geist, Geist_Mono, Cairo } from "next/font/google";

const geistSans = Geist({
  variable: "--font-en",
  subsets: ["latin"],
});

const arabicFont = Cairo({
  variable: "--font-ar",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
            ${geistSans.variable}
            ${arabicFont.variable}
            antialiased
            font-sans
          `}
      >
        <div className="grid min-h-screen grid-cols-[1fr_313px]">
          <main className="p-6">{children}</main>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
