import type { Metadata } from "next";
import "../globals.css";
import { Geist, Cairo } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import LayoutProvider from "../components/LayoutProvider";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-en",
  subsets: ["latin"],
});

const arabicFont = Cairo({
  variable: "--font-ar",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html lang={locale} dir={hasLocale(["ar"], locale) ? "rtl" : "ltr"}>
      <body
        className={`
          ${geistSans.variable}
          ${arabicFont.variable}
          antialiased
          font-sans
        `}
      >
        <NextIntlClientProvider messages={messages || {}}>
          <LayoutProvider>
            <main className="grow">
              {children}
            </main>
          </LayoutProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
